/** Declaration file generated by dts-gen */

declare module "mali" {
  export default class mali {
    constructor(...args: any[]);

    addService(...args: any[]): void;

    callback(...args: any[]): void;

    close(...args: any[]): void;

    inspect(...args: any[]): void;

    onerror(...args: any[]): void;

    start(...args: any[]): void;

    toJSON(...args: any[]): void;

    use(...args: any[]): void;

    static defaultMaxListeners: number;

    static init(): void;

    static listenerCount(emitter: any, type: any): any;

    static usingDomains: boolean;

  }

}

