from node:8-alpine
MAINTAINER Joe Miyamoto <joemphilips@gmail.com>
SHELL ["/bin/sh", "-c"]

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apk add --no-cache alpine-sdk python # for node-gyp

COPY package.json /usr/src/app/package.json
COPY yarn.lock /usr/src/app/yarn.lock
COPY ./tsconfig.* ./lerna.json /usr/src/app/


COPY packages/core \
  /usr/src/app/packages/core/
COPY packages/components \
  /usr/src/app/packages/components/
COPY packages/blockchain-driver \
  /usr/src/app/packages/blockchain-driver
COPY packages/walletts-app \
  /usr/src/app/packages/walletts-app/

RUN npm install -g lerna
RUN yarn bootstrap
RUN yarn build
