/** Declaration file generated by dts-gen */

declare module 'bcurl' {
  export class Client {
    constructor(...args: any[]);

    auth(...args: any[]): void;

    bind(...args: any[]): void;

    call(...args: any[]): void;

    clone(...args: any[]): void;

    close(...args: any[]): void;

    del(...args: any[]): void;

    execute(...args: any[]): void;

    fire(...args: any[]): void;

    get(...args: any[]): void;

    hook(...args: any[]): void;

    open(...args: any[]): void;

    post(...args: any[]): void;

    put(...args: any[]): void;

    request(...args: any[]): void;

    static defaultMaxListeners: number;

    static init(): void;

    static listenerCount(emitter: any, type: any): any;

    static usingDomains: boolean;
  }

  export function client(options: any): void;
}
